
#ifndef GEOARROW_CONFIG_H_INCLUDED
#define GEOARROW_CONFIG_H_INCLUDED

#define GEOARROW_VERSION_MAJOR 0
#define GEOARROW_VERSION_MINOR 1
#define GEOARROW_VERSION_PATCH 0
#define GEOARROW_VERSION "0.1.0-SNAPSHOT"

#define GEOARROW_VERSION_INT \
(GEOARROW_VERSION_MAJOR * 10000 + GEOARROW_VERSION_MINOR * 100 + GEOARROW_VERSION_PATCH)

#define GEOARROW_USE_FAST_FLOAT 1

#define GEOARROW_USE_RYU 1

#endif
