#define R_NO_REMAP
#include <R.h>
#include <R_ext/Rdynload.h>
#include <Rinternals.h>

/* generated by tools/make-callentries.R */
extern SEXP geoarrow_c_kernel(SEXP kernel_name_sexp, SEXP arg_types_sexp,
                              SEXP options_sexp, SEXP schema_out_xptr);
extern SEXP geoarrow_c_kernel_push(SEXP kernel_xptr, SEXP args_sexp, SEXP array_out_xptr);
extern SEXP geoarrow_c_kernel_finish(SEXP kernel_xptr, SEXP array_out_xptr);
extern SEXP geoarrow_c_as_nanoarrow_array_sfc(SEXP sfc, SEXP schema_xptr,
                                              SEXP array_xptr);
extern SEXP geoarrow_c_make_type(SEXP geometry_type_sexp, SEXP dimensions_sexp,
                                 SEXP coord_type_sexp);
extern SEXP geoarrow_c_schema_init_extension(SEXP schema_xptr, SEXP type_sexp);
extern SEXP geoarrow_c_schema_parse(SEXP schema_xptr, SEXP extension_name_sexp);
extern SEXP geoarrow_c_handle_stream(SEXP data, SEXP handler_xptr);
extern SEXP geoarrow_c_writer_new(SEXP schema_xptr, SEXP array_out_xptr);

static const R_CallMethodDef CallEntries[] = {
    {"geoarrow_c_kernel", (DL_FUNC)&geoarrow_c_kernel, 4},
    {"geoarrow_c_kernel_push", (DL_FUNC)&geoarrow_c_kernel_push, 3},
    {"geoarrow_c_kernel_finish", (DL_FUNC)&geoarrow_c_kernel_finish, 2},
    {"geoarrow_c_as_nanoarrow_array_sfc", (DL_FUNC)&geoarrow_c_as_nanoarrow_array_sfc, 3},
    {"geoarrow_c_make_type", (DL_FUNC)&geoarrow_c_make_type, 3},
    {"geoarrow_c_schema_init_extension", (DL_FUNC)&geoarrow_c_schema_init_extension, 2},
    {"geoarrow_c_schema_parse", (DL_FUNC)&geoarrow_c_schema_parse, 2},
    {"geoarrow_c_handle_stream", (DL_FUNC)&geoarrow_c_handle_stream, 2},
    {"geoarrow_c_writer_new", (DL_FUNC)&geoarrow_c_writer_new, 2},
    {NULL, NULL, 0}};
/* end generated by tools/make-callentries.R */

void R_init_geoarrow(DllInfo* dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
